name = input("what is your name? :")
surname = input("what is your surname? :")
age = input("how old are you? :")
place = input("where do you live? :")
hobby = input("what is your hobby? :")
print("შენი სახელი და გვარია" + " " + name + " " + surname )
print("შენი ასაკია" + " " + age + " " + "ცხოვრობ" + " " + place + "-ში" + " " + "შენი ჰობი" + " " + hobby)